### ISSUE TITLE
Update to new github set output commands

### ISSUE THREAD

**Issue by ray-peters** [Jtalk/url-health-check-action#16]
The following warnings started bubbling up inside github action workflows:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Is it possible to get an update to support the new commands and resolve the warning?

https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

**Comment by Jtalk** [comment]
Hey @ray-peters, thanks for flagging this. I've now pushed v2.3, it should've resolved the warnings. The CI looked clean, but let me know if anything.

**Comment by ray-peters** [comment]
@Jtalk We updated to the latest version v2.3, verified the integration works as expected, and the warnings are gone. Thank you very much!
