### ISSUE TITLE
Node 12 deprecation warning

### ISSUE THREAD

**Issue by erose-wwt** [Jtalk/url-health-check-action#19]
Getting this warning.  Are there plans to move to node 16?

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: jtalk/url-health-check-action, jtalk/url-health-check-action

**Comment by Jtalk** [comment]
v3 is now running on Node 16, cheers
