### ISSUE TITLE
Retry on connection refused

### ISSUE THREAD

**Issue by benmerckx** [Jtalk/url-health-check-action#4]
Curl fails immediately (skipping retries) when connection on the port is refused. Might make sense to add `--retry-connrefused`?

**Comment by Jtalk** [comment]
Hey @benmerckx, thanks for this suggestion! I can't remember why it wasn't added straight away, but I can't think of any reason not to do it now.

v1.4 is now available and should have this enabled by default. 

It seems to have passed all the checks, but let me know if anything.
