### ISSUE TITLE
retry-all doesn't work on ubuntu-latest (08/26/2021)

### ISSUE THREAD

**Issue by seveibar** [Jtalk/url-health-check-action#6]
![image](https://user-images.githubusercontent.com/1910070/131014651-8fef149d-568d-488d-aaf3-56d50145fab6.png)

**Comment by Jtalk** [comment]
It doesn't work because your curl is out of date. Not sure what exactly I can do about it. Any specific suggestions?

**Comment by acron0** [comment]
Is there a base image you know that _does_ work?

**Comment by Jtalk** [comment]
@acron0 `macos-current` should work. I don't think any of the rest of the github-owned runners will do. 

But I think I've come up with a solution. The [v2](https://github.com/Jtalk/url-health-check-action/releases/tag/v2) version should now download a newer curl when `retry-all` is set & the system one is too old to support it. Apart from providing a more descriptive error,  this is the only thing I can do until Github switches to Ubuntu 21.04.
